Feature: Scraping using Microsoft Teams
mkamadeus/nicscraper pull request #2
Opened 2022-12-18 15:06 UTC by IloveNooodles

Here's my PR regarding the new scraping method using microsoft teams

Summary of changes
1. New Student model
2. New Request Model
3. New Response Model
4. New method on getbynim, writer, start, and receive

![PR-Gare](https://user-images.githubusercontent.com/63847012/208305547-61c95613-879d-4c84-b466-33d90f629d80.gif)

Note: Somehow the writer still output empty user

2022-12-19 14:26 UTC, mkamadeus commented on models/arguments.go
> +	Jwt            string            `arg:"-j,--jwt,env:JWT_TOKEN" help:"Set jwt token via argument, also accept from JWT_TOKEN environment variable"`
- `JWT` instead of `Jwt`
-  Help message would be better if written like the following: `Set JWT token via argument, can also be set via JWT_TOKEN environment variable`

2022-12-19 14:26 UTC, mkamadeus commented on models/arguments.go
> +	Cvid           string            `arg:"-c,--cvid,env:CVID_TOKEN" help:"Set cvid token via argument, also accept from CVID_TOKEN via environment variable"`
- `CVID` instead of `Cvid`
-  Help message would be better if written like the following: `Set CVID token via argument, can also be set via CVID_TOKEN environment variable`

2022-12-19 14:27 UTC, mkamadeus commented on main.go
> +	if s.Args.UseTeams {
I would be okay by making this the default method; perhaps can use the opposite flag (e.g:  `--use-nic` when scraping from NIC)

2022-12-19 14:28 UTC, mkamadeus commented on readme.md
> +## NEW MODE!!!: Teams Scrap
Will fix grammar later 😄

2022-12-19 14:32 UTC, mkamadeus commented on utils/constants/nimtostring.go
> +var NIMToString = map[string]string{
Consider using `embed`
https://pkg.go.dev/embed

Can create the JSON file separately for better maintenance/readibility

2022-12-19 14:33 UTC, mkamadeus commented on models/reponse.go
> +package models
Filename should be `response.go`

2022-12-19 14:35 UTC, mkamadeus commented on scraper/base.go
>  package scraper
Related to [this comment](https://github.com/mkamadeus/nicscraper/pull/2/files#r1052261918), consider splitting the code/create new `Scraper` type (e.g `TeamsScraper`/something similar) to create a distinction between the scraping methods

2022-12-19 14:36 UTC, mkamadeus requested changes
Refer to the comments given

2022-12-19 14:38 UTC, mkamadeus commented
Related to https://github.com/mkamadeus/geprek-nim-finder/issues/5
cc: @atpur-rafif

2022-12-19 17:08 UTC, IloveNooodles commented on readme.md
> +## NEW MODE!!!: Teams Scrap
Noted :D

2022-12-19 18:42 UTC, IloveNooodles commented on scraper/base.go
>  package scraper
done

2022-12-19 18:45 UTC, IloveNooodles commented on main.go
> +	if s.Args.UseTeams {
Hmm i wouldn't recommend it though, because teams searching algorithm is kinda weird and it **doesn't hold the previous NIM values, only the latest one**. So for example if you search `-p 165 -y 20` it will output the `major` NIM instead of the `faculty` one because they already got their major NIM

2022-12-20 01:14 UTC, mkamadeus commented on main.go
> +	if s.Args.UseTeams {
Then should we make it a subcommand? Looks better IMO

2022-12-29 20:43 UTC, IloveNooodles commented
@mkamadeus done ya, new method --connection teams and nic 
![image](https://user-images.githubusercontent.com/63847012/210009046-755f2c69-2eee-4cb5-8b64-302a6c3a1d40.png)

Me testing to get ALL nim

2023-01-07 10:50 UTC, mkamadeus approved these changes
LGTM!

2023-01-07 10:50 UTC, merged